name = 'whatsapp-api'
main = "src/index.js"
compatibility_date = "2024-06-01"

[[d1_databases]]
binding = "DB"
database_name = "vinet-whatsapp-db"
database_id = "2e1228d6-b6f6-494e-b4de-9cdd508854a0"

[[r2_buckets]]
binding = "vinet_whatsapp_images"
bucket_name = "vinet-whatsapp-images"

[[kv_namespaces]]
binding = "KV_BINDING"
id = "f67b068e3dc8441a97c8c68212cb6d61"

[vars]
PHONE_NUMBER_ID = "104043025887306"
WHATSAPP_TOKEN = "EAALpZCXUFpXsBO9tCyAuJUdO9MObRocFxZAZCJlxheOZBNp8CTvDn1Was9K48VkK3G3QZADZCYKur24nnXe9FNmwaCuttnzgOezJQi9tZApBZCVaq9ZCsID3FxlvJb6E1p7uLZADEtNoRRpiLGL3UCCY0ZBVp4YxxZC7TL3iIGvaqDH6hwQbZAIToVJeVceeAQjEkyxQZD"
VERIFY_TOKEN = "vinet-whatsapp"
BUSINESS_ID = "416413345495591"

[observability.logs]
enabled = true



